[2022-11-17 09:18:03,198] [builder.py:193]            [INFO]     |====================================================================================================|
[2022-11-17 09:18:03,198] [builder.py:193]            [INFO]     |                                Alien Collection in Christmas Movies                                |
[2022-11-17 09:18:03,199] [builder.py:193]            [INFO]     |====================================================================================================|
[2022-11-17 09:18:03,199] [builder.py:194]            [INFO]     |                                                                                                    |
[2022-11-17 09:18:03,199] [builder.py:199]            [INFO]     |================================ Building Definition From Templates ================================|
[2022-11-17 09:18:03,199] [builder.py:215]            [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,200] [meta.py:210]               [DEBUG]    |======================================= Template Collection ========================================|
[2022-11-17 09:18:03,200] [meta.py:451]               [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,202] [meta.py:512]               [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,202] [meta.py:513]               [DEBUG]    |==================================== Final Template Attributes =====================================|
[2022-11-17 09:18:03,203] [meta.py:514]               [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,203] [meta.py:515]               [DEBUG]    | {'tmdb_collection': '8091, 135416', 'tmdb_summary': 135416, 'url_poster': '<<poster>>', 'sort_title': '+4_Alien', 'sync_mode': 'sync', 'collection_order': 'release'} |
[2022-11-17 09:18:03,203] [meta.py:516]               [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,203] [builder.py:223]            [INFO]     |=================================== Validating Alien Attributes ====================================|
[2022-11-17 09:18:03,203] [builder.py:516]            [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,203] [builder.py:517]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-11-17 09:18:03,204] [builder.py:521]            [DEBUG]    | Value: sync                                                                                        |
[2022-11-17 09:18:03,204] [builder.py:613]            [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,204] [builder.py:614]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-11-17 09:18:03,204] [builder.py:615]            [DEBUG]    | Value: release                                                                                     |
[2022-11-17 09:18:03,204] [builder.py:646]            [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,204] [builder.py:650]            [DEBUG]    | Validating Method: tmdb_collection                                                                 |
[2022-11-17 09:18:03,204] [builder.py:651]            [DEBUG]    | Value: 8091, 135416                                                                                |
[2022-11-17 09:18:03,240] [builder.py:646]            [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,241] [builder.py:650]            [DEBUG]    | Validating Method: tmdb_summary                                                                    |
[2022-11-17 09:18:03,241] [builder.py:651]            [DEBUG]    | Value: 135416                                                                                      |
[2022-11-17 09:18:03,255] [builder.py:646]            [DEBUG]    |                                                                                                    |
[2022-11-17 09:18:03,256] [builder.py:650]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-11-17 09:18:03,256] [builder.py:651]            [DEBUG]    | Value: <<poster>>                                                                                  |
[2022-11-17 09:18:53,307] [plex_meta_manager.py:730]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 592, in run_collection
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str)
                                                                 |   File "/modules/builder.py", line 702, in __init__
                                                                 |     self._poster(method_name, method_data)
                                                                 |   File "/modules/builder.py", line 840, in _poster
                                                                 |     image_response = self.config.get(method_data, headers=util.header())
                                                                 |   File "/usr/local/lib/python3.10/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/usr/local/lib/python3.10/site-packages/retrying.py", line 212, in call
                                                                 |     raise attempt.get()
                                                                 |   File "/usr/local/lib/python3.10/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/usr/local/lib/python3.10/site-packages/six.py", line 719, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/local/lib/python3.10/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "/modules/config.py", line 987, in get
                                                                 |     return self.session.get(url, json=json, headers=headers, params=params)
                                                                 |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
                                                                 |     return self.request("GET", url, **kwargs)
                                                                 |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
                                                                 |     prep = self.prepare_request(req)
                                                                 |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
                                                                 |     p.prepare(
                                                                 |   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
                                                                 |     self.prepare_url(url, params)
                                                                 |   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
                                                                 |     raise MissingSchema(
                                                                 | requests.exceptions.MissingSchema: Invalid URL '<<poster>>': No scheme supplied. Perhaps you meant http://<<poster>>?
                                                                 | 
[2022-11-17 09:18:53,312] [plex_meta_manager.py:731]  [ERROR]    | Unknown Error: Invalid URL '<<poster>>': No scheme supplied. Perhaps you meant http://<<poster>>?
[2022-11-17 09:18:53,312] [plex_meta_manager.py:736]  [INFO]     | 
[2022-11-17 09:18:53,312] [plex_meta_manager.py:737]  [INFO]     |====================================================================================================|
[2022-11-17 09:18:53,312] [plex_meta_manager.py:737]  [INFO]     |                                     Finished Alien Collection                                      |
[2022-11-17 09:18:53,313] [plex_meta_manager.py:737]  [INFO]     |                                    Collection Run Time: 0:00:50                                    |
[2022-11-17 09:18:53,313] [plex_meta_manager.py:737]  [INFO]     |====================================================================================================|
